import { createRequire } from 'node:module'
import QRCode from 'qrcode'
import jsQR from 'jsqr'
import { describe, expect, it } from 'vitest'
import { QR_OPTIONS, QR_PNG_WIDTH, QR_PRESETS } from './qr-code-presets.config'

// Decode the generated bytes using QRCode's PNG reader dependency, followed
// by an independent QR decoder. No mocked encoder or browser canvas is used.
const require = createRequire(import.meta.url)
const { PNG } = createRequire(require.resolve('qrcode'))('pngjs') as {
  PNG: { sync: { read(buffer: Buffer): { width: number; height: number; data: Buffer } } }
}

describe.each([
  'https://genealogiq.app/profile/qa-human-memorial',
  'https://genealogiq.app/profile/qa-pet-memorial',
  'https://genealogiq.app/qr/EXISTING-CODE',
])('printable QR destination %s', (destination) => {
  it.each(QR_PRESETS)('decodes the real $key PNG and produces vector SVG', async (preset) => {
    const options = { ...QR_OPTIONS, color: { dark: preset.fg, light: preset.bg } }
    const dataUrl = await QRCode.toDataURL(destination, { ...options, width: QR_PNG_WIDTH })
    expect(dataUrl).toMatch(/^data:image\/png;base64,/)
    const png = PNG.sync.read(Buffer.from(dataUrl.split(',')[1], 'base64'))
    // QRCode rounds a fractional module scale down by one pixel for some URLs.
    expect([1023, 1024]).toContain(png.width)
    expect(png.height).toBe(png.width)
    const decoded = jsQR(Uint8ClampedArray.from(png.data), png.width, png.height)
    expect(decoded?.data).toBe(destination)

    const svg = await QRCode.toString(destination, { ...options, type: 'svg' })
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"')
    expect(svg).toContain('<path')
    expect(svg).not.toContain('<image')
  })
})
